### ISSUE TITLE
Починить слайдер в компоненте дизайна

### ISSUE THREAD

**Issue by dapi** [merchantly/front-public#142]
![image](https://user-images.githubusercontent.com/37688386/48115375-bf18f380-e273-11e8-9650-036988fb04e3.png)

![2018-12-07 17 44 57](https://user-images.githubusercontent.com/37688386/49654071-e405af80-fa47-11e8-8120-846117d1e9f8.png)

Слайдер переключения количества строк товаров уехал влево

**Comment by dapi** [comment]
@irakiosk кинь ссылку на магазин с примером где это можно проверить

**Comment by irakiosk** [comment]
http://21xiaomi.ru/
